src/localito/urls.py
from django.contrib import admin
from django.urls import path, include

from restaurants.views import (
    restaurantView,
    cartView,
    lastStepFormView,
    thankyou_view
)
from pagemanager.views import homeScreenView
from account.views import registerView, logoutView, loginView

#Images config
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('', homeScreenView, name="home"),
    path('registro/', registerView, name='register'),
    path('logout/', logoutView, name='logout'),
    path('acceder/', loginView, name='login'),
    path('<str:restaurant>/', restaurantView, name='restaurant'),
    path('<str:restaurant>/cart/', cartView, name='cart'),
    path('<str:restaurant>/checkout/id=<int:orderId>', lastStepFormView, name='checkout'),
    path('<str:restaurant>/thank-you/id=<int:orderId>', thankyou_view, name='thankyouorder'),
    path('ajax/', include('restaurants.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/restaurants/urls.py
from django.urls import path

from restaurants.views import (
    newItemOrderView,
    updateOrderView,
    setOrderView,
    cartView,
    addDeliveryView,
    removeDeliveryView,
    lastStepFormView,
    addDeliveryDetailsView,
    order_success_view
)

urlpatterns = [
    path('newitemorder', newItemOrderView, name='newItemOrder'),
    path('updateorder', updateOrderView, name='updateOrder'),
    path('setorder', setOrderView, name='setOrder'),
    path('add-delivery', addDeliveryView, name='addDelivery'),
    path('remove-delivery', removeDeliveryView, name='removeDelivery'),
    path('add-delivery-details', addDeliveryDetailsView, name='addDeliveryDetails'),
    path('order-success', order_success_view, name='order-success')
]

src/restaurants/models.py
from django.db import models
from account.models import Account
from django.utils.text import slugify
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField
from .symbols import symbols
import urllib.parse
import pyqrcode
from PIL import Image
from django.urls import reverse
from io import BytesIO
from django.contrib.sites.shortcuts import get_current_site
from django.core.files import File
import os



class Restaurant(models.Model):
    owner                   = models.ForeignKey(Account, default=None, on_delete=models.CASCADE, blank=True)
    name                    = models.CharField(max_length=60, verbose_name='Nombre de tienda')
    slug                    = models.SlugField(unique=True, blank=True)
    address                 = models.CharField(max_length=80, blank=True, verbose_name='Dirección')
    currency                = models.CharField(choices=symbols, max_length=30, default='USD')
    city                    = models.CharField(max_length=60, blank=True)
    country                 = models.CharField(max_length=60, blank=True)
    store_country           = CountryField(blank=True)
    postal_code             = models.CharField(max_length=60, blank=True)
    business_hours          = models.CharField(max_length=30, blank=True)
    image                   = models.ImageField(upload_to='restaurant-images', verbose_name='Logo de Restaurante', blank=True)
    about                   = models.TextField(max_length=300, blank=True)
    delivery_price          = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    whatsapp_number         = PhoneNumberField(blank=True)
    facebook_url            = models.URLField(max_length=60, blank=True, verbose_name="Link de Facebook")
    instagram_url           = models.URLField(max_length=60, blank=True, verbose_name="Link de Instagram")
    qr_code                 = models.ImageField(upload_to='qr-codes', verbose_name='Código QR', blank=True, null=True)

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if not self.qr_code:
            memfile = BytesIO()

            qr = pyqrcode.QRCode(self.storeURL)
            qr.png(memfile, scale=10)
            self.qr_code.save(self.slug + '.png', File(memfile), save=False)
            super(Restaurant, self).save(*args, **kwargs)
            print('generated QR')
            memfile.close()

        # try:
        #     url = self.qr_code.url
        #     image_path = urlparse(url)
        #     file_name = os.path.basename(image_path.path)

        #     if self.slug not in file_name:
        #         print('oooh no')
        #         raise Exception()


    def get_social_links(self):
        links = {}
        if self.facebook_url:
            links['fa-facebook-f'] = self.facebook_url
        if self.instagram_url:
            links['fa-instagram'] = self.instagram_url
        return links
    
    @property
    def get_full_address(self):
        address = ''
        if self.address:
            address += self.address
        if self.city:
            address += ', ' + self.city
        if self.country:
            address += ', ' + self.country
        return address
    
    @property
    def imageURL(self):
        try:
            url = self.image.url    
        except:
            url = False
        return url
    
    @property
    def storeURL(self):
        request = None
        domain = get_current_site(request).domain
        url = 'http://' + domain + reverse('restaurant', args=(self.slug,))
        return url



class Section(models.Model):
    restaurant              = models.ForeignKey(Restaurant, default=None, on_delete=models.CASCADE, blank=True)
    name                    = models.CharField(max_length=20, blank=True)
    description             = models.TextField(max_length=300, blank=True)
    order                   = models.IntegerField(default=0)

    def __str__(self):
        return self.name + ' - ' + self.restaurant.name

class Product(models.Model):
    section                 = models.ForeignKey(Section, default=None, on_delete=models.CASCADE, blank=True)
    name                    = models.CharField(max_length=60, blank=True)
    description             = models.TextField(max_length=150, blank=True)
    image                   = models.ImageField(upload_to='products', blank=True)
    price                   = models.DecimalField(max_digits=7, decimal_places=2)

    def __str__(self):
        return self.name + ' - ' + self.section.name + ' - ' + self.section.restaurant.name

class Customer(models.Model):
    user                    = models.OneToOneField(Account, null=True, blank=True, on_delete=models.CASCADE)
    name                    = models.CharField(max_length=200, null=True)
    email                   = models.EmailField(max_length=60)
    phone                   = PhoneNumberField(blank=True, null=True)
    address                 = models.CharField(max_length=200, null=True, blank=True)
    device                  = models.CharField(max_length=300, null=True, blank=True)

    def __str__(self):
        return self.device

class Order(models.Model):
    customer                = models.ForeignKey(Customer,on_delete=models.CASCADE, blank=True, null=True)
    restaurant              = models.ForeignKey(Restaurant,on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered            = models.DateTimeField(auto_now_add=True)
    complete                = models.BooleanField(default=False)
    is_delivery             = models.BooleanField(default=True, null=True, blank=True)
    is_payed                = models.BooleanField(default=False)
    notes                   = models.TextField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderItems          = self.orderitem_set.all()
        total               = sum([item.get_total for item in orderItems])
        return total
    
    @property
    def get_order_products(self):
        orderItems = self.orderitem_set.all()
        return orderItems

    @property 
    def get_cart_items(self):
        orderItems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderItems])
        return total
    
    @property
    def whatsapp_link(self):
        total = self.get_cart_total
        delivery_price = self.restaurant.delivery_price
        restaurant_name = self.restaurant.name
        client_name = self.customer.name
        client_address = self.customer.address

        all_products = self.get_order_products
        product_list = ""

        for item in all_products:
            quantity = item.quantity
            if quantity > 0:
                item_name = '\n' + '-' + str(quantity) + ' x ' + item.product.name + ' (' + str(item.get_total) + ')'
                product_list += item_name
                
        if self.is_delivery and delivery_price > 0:
            total += self.restaurant.delivery_price
            product_list += '\n' + '-Envío a domocilio' + ' (' + str(delivery_price) + ')'

        message = f"Hola {restaurant_name} soy *{client_name}* y quiero hacer un pedido para la dirección *{client_address}*:\n{product_list}\n\n*Total: {total}*\n\n¡Gracias!"
        encoded_message = urllib.parse.quote(message)
        phone = str(self.restaurant.whatsapp_number).replace('+','')

        return "https://wa.me/" + phone + "?text=" + encoded_message



class OrderItem(models.Model):
    product                 = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order                   = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)
    quantity                = models.PositiveIntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return str(self.product.name)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

    

src/restaurants/forms.py
from django import forms
from django.forms import widgets
from .models import (
    Restaurant,
    Product, 
    Customer, 
    Order, 
    OrderItem,
    )

from phonenumber_field.formfields import PhoneNumberField

# class createCustomer(forms.ModelForm):
#     class Meta:
#         model = Customer
#         fields = ['device']


# class createOrder(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['customer', 'restaurant']


# class addOrderItem(forms.ModelForm):
#     class Meta:
#         model = OrderItem
#         fields = ['product','order', 'quantity']

class submitOrderForm(forms.ModelForm):
    name = forms.CharField(max_length=60, label='Nombre', widget=forms.TextInput(attrs={'class':'input','autocomplete':'name'}))
    address = forms.CharField(max_length=60, label='Dirección de Entrega', widget=forms.TextInput(attrs={'class':'input','autocomplete':'address'}))
    # email = forms.EmailField(max_length=60, label='Correo Electronico (Opcional)', widget=forms.EmailInput(attrs={'class':'input','autocomplete':'email'}), required=False)
    phone = PhoneNumberField(label='Número de WhatsApp', widget=forms.TextInput(attrs={'class':'input'}))

    class Meta:
        model = Customer
        fields = ['name', 'address', 'phone']

class orderNotesForm(forms.ModelForm):
    notes = forms.CharField(label='Añadir nota', widget=forms.Textarea(attrs={'class':'textarea', 'rows':'2', 'placeholder':'Enviar salsa extra, más servilletas...'}), required=False)
    class Meta:
        model = Order
        fields = ['notes']

src/restaurants/templates/restaurants/last_step.html
{% load static %}

<!DOCTYPE html>

{% autoescape off %}
<html lang="es-mx" data-slug={{ slug }} data-currency={{ currency }}>
{% endautoescape %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ name }} | Localito </title>

    <!-- Bulma -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css" integrity="sha512-IgmDkwzs96t4SrChW29No3NXBIBv8baW490zk5aXvhCD8vuZM3yUSkbyTBcXohkySecyzIrUwiF/qV0cuPcL3Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Style -->
    <link rel="stylesheet" href='{% static "css/restaurant.css" %}'>
    
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- Phone Input -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css" integrity="sha512-gxWow8Mo6q6pLa1XH/CcH8JyiSDEtiwJV78E+D+QP0EVasFs8wKXq16G8CLD4CJ2SnonHr4Lm/yY2fSI2+cbmw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/intlTelInput.min.js" integrity="sha512-QMUqEPmhXq1f3DnAVdXvu40C8nbTgxvBGvNruP6RFacy3zWKbNTmx7rdQVVM2gkd2auCWhlPYtcW2tHwzso4SA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Paypal -->
    <script src="https://www.paypal.com/sdk/js?client-id=AZUjiK_UGGkbn4giigU1e1VNKZsNJzE-ijIyrtoUVwhNeXnGzfrNSVwpUeDFTgNsWaqhOVPttbocBcrC&currency=MXN"></script>
    
</head>

<body>

    <!-- Header section -->
    <section class="hero is-primary has-text-centered is-small">
        <div class="hero-body ">
            <div class="container">
                <img src={{ image }} alt="" class="restaurant-img mb-3">
                <h1 class="title is-4">
                    {{ name }}
                </h1>         
            </div>
        </div>
    </section>
    <!-- End Header section -->

    <div class="container has-text-centered py-4 ">
        <div class="columns is-mobile is-vcentered">
            <div class="column">
                <span class="icon is-medium">
                    <i class="fas fa-user-check"></i>
                </span>
                <span>
                    <h2 class="subtitle is-4">
                        Completa tu información
                    </h2>
                </span>
            </div>
        </div>
    </div>

    <section id="orderInfo" class="info is-medium is-fullheight" data-orderId="{{ orderId }}">
        <div class="container">
            <div class="column is-10 is-offset-1">

                <div class="card">
                    <div class="card-content">

                        <form method=post>
                            {% csrf_token %}

                            {% for non_field_error in client_form.non_field_errors %}
                            <div class="notification is-danger">{{ non_field_error }}</div>
                            {% endfor %}

                            {% for non_field_error in order_notes_form.non_field_errors %}
                            <div class="notification is-danger">{{ non_field_error }}</div>
                            {% endfor %}

                            {% for field in client_form %}

                                {% if field.id_for_label == 'id_address' and order_is_delivery is not True %}

                                {% else %}
                                
                                <div class="field">
                                    <label for="{{ field.id_for_label }}" class="label">{{field.label}}</label>
                                    {{field}}
                                </div>
        
                                    {% if field.help_text %}
                                        <p class="help" style="padding-bottom: 5px">{{field.help_text}}</p>
                                    {% endif %} 
            
                                    {% for error in field.errors %}
                                        <p class="help is-danger" style="padding-bottom:5px">{{error}}</p>
                                    {% endfor %}
                                {% endif %}

                            {% endfor %}

                            {% for field in order_notes_form %}
                            <div class="field">
                                <label for="{{ field.id_for_label }}" class="label">{{field.label}}</label>
                                {{field}}
                            </div>
    
                                {% if field.help_text %}
                                    <p class="help" style="padding-bottom: 5px">{{field.help_text}}</p>
                                {% endif %} 
        
                                {% for error in field.errors %}
                                    <p class="help is-danger" style="padding-bottom:5px">{{error}}</p>
                                {% endfor %}

                            {% endfor %}

                            <hr>

                            <div>
                                
                                <h3 class="title is-5">Método de pago</h3>

                                <div id='payment-methods-warning' class="notification is-warning is-light">
                                    <p>Ingresa tus datos para ver los métodos de pago</p>
                                </div>

                                <div id="payment-methods-selector" class="control">
                                    <label class="radio">
                                      <input type="radio" name="answer" checked>
                                      Tarjeta de crédito o débito (Paypal)
                                    </label>
                                    
                                    <div id="paypal-button-container" class="py-4 has-text-centered"></div>
                                    
                                    <label class="radio">
                                      <input type="radio" name="answer">
                                      Efectivo
                                    </label>
                                </div>

                            </div>

                        </form>


                        <!-- <a id="whatsapp-link" target="_blank" rel="noopener noreferrer" class="button is-fullwidth is-rounded is-success mt-5" disabled="disabled">
                            <span class="icon">
                                <i class="fab fa-lg fa-whatsapp"></i>
                            </span>
                            <span class="has-text-weight-bold">
                                &nbsp;&nbsp;Pedir por WhatsApp
                            </span>
                        </a> -->


                        <a href="{% url 'restaurant' slug %}" class="button is-fullwidth is-rounded is-warning mt-4">
                            <span class="icon">
                                <i class="fas fa-undo-alt"></i>
                            </span>
                            <span>Volver a la tienda</span>
                        </a>
                    </div>
                </div>


            </div>
        </div>
    </section>


    <!-- Localito watermark -->
    <section class="has-text-centered py-5">
        Powered by Localito
    </section>

</body>

<footer>

    <script>

        $(document).ready(function() {

            function getIp(callback) {
                    fetch('https://ipinfo.io/json?token=ad29c6a41a339b', { headers: { 'Accept': 'application/json' }})
                    .then((resp) => resp.json())
                    .catch(() => {
                        return {
                        country: 'us',
                        };
                    })
                    .then((resp) => callback(resp.country));
                }
                
            const phoneInputField = document.querySelector("#id_phone");
            const phoneInput = window.intlTelInput(phoneInputField, {
                preferredCountries: ['mx','us','co','ar'],
                initialCountry: "auto",
                geoIpLookup: getIp,
                utilsScript:
                "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/utils.js",
            });

            let order_total = '{{ order_total }}';
            let csrf_token = '{{ csrf_token }}';
            let orderId = $('#orderInfo').attr('data-orderId');

            let name_val = $('#id_name').val();
            let address_val = $('#id_address').val();
            let notes_val = $('#id_notes').val();

            let payment_element = $('#payment-methods-selector');
            let payment_warning = $('#payment-methods-warning');
            payment_element.addClass('is-hidden');

            paypal.Buttons({
                
                style: {
                    color: 'blue',
                    shape: 'pill',   
                },
                
                onInit: function(data, actions) {
                    // actions.disable();
                },

                // Sets up the transaction when a payment button is clicked
                createOrder: function(data, actions) {
                    
                    return actions.order.create({
                        purchase_units: [{
                            amount: {
                            value: order_total // Can reference variables or functions. Example: `value: document.getElementById('...').value`
                            }
                        }],
                    });
                },

                // Finalize the transaction after payer approval
                onApprove: function(data, actions) {
                    return actions.order.capture().then(function(orderData) {
                    // Successful capture! For dev/demo purposes:
                        console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                        var transaction = orderData.purchase_units[0].payments.captures[0];
                        alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                        var redirect_url = ''

                        $.ajax({
                            url: '{% url "order-success" %}',
                            type: 'post',
                            data: {
                                'customer_name': name_val,
                                'customer_address': address_val,
                                'notes': notes_val,
                                'csrfmiddlewaretoken': csrf_token,
                                'orderId': orderId,
                                'customer_phone': phoneInput.getNumber(),
                            },
                            success: function(response) {
                                redirect_url= response.url
                                console.log(redirect_url)
                                window.location.href = redirect_url
                                // actions.redirect(redirect_url)
                                }
                        });

                    });
                }
                }).render('#paypal-button-container');
                
                $('#id_name, #id_phone').keyup(function(e) {
                        let len_name = $('#id_name').val().length;
                        let valid_number = phoneInput.isValidNumber();
                        // let len_phone = phoneInput.getNumber().length
                        let phone_input = $('#id_phone');
                        let name_input = $('#id_name');

                        if ((len_name > 0) && (valid_number)){
                            // actions.enable();
                            payment_element.removeClass('is-hidden');
                            payment_warning.addClass('is-hidden');
                            phone_input.addClass('is-success');
                            name_input.addClass('is-success')

                        } else {
                            // actions.disable();
                            payment_element.addClass('is-hidden');
                            payment_warning.removeClass('is-hidden');
                            phone_input.removeClass('is-success');
                            name_input.removeClass('is-success');
                        };
                        
                    });

            });

    </script>

</footer>

</html>

src/restaurants/templates/restaurants/thank-you.html
{% load static %}

<!DOCTYPE html>

{% autoescape off %}
<html lang="es-mx" data-currency={{ currency }}>
{% endautoescape %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Bulma -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css" integrity="sha512-IgmDkwzs96t4SrChW29No3NXBIBv8baW490zk5aXvhCD8vuZM3yUSkbyTBcXohkySecyzIrUwiF/qV0cuPcL3Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Style -->
    <link rel="stylesheet" href='{% static "css/restaurant.css" %}'>
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

</head>

<style>
    .animation-block {
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .vcenter-card {
        display: flex;
        justify-content: center;
        align-items: center;
        min-width: 50%;
        max-width: 95%;
    }

    /* .container-thin-margin {
        margin: 15px;
    } */
</style>

<body>

    <section class="hero is-fullheight">
        <div class="container vcenter-card container-thin-margin">
            <div class="column">
                <div class="card">
                    <div class="card-content">

                        <div class="animation-block">
                            <lottie-player src="https://assets2.lottiefiles.com/private_files/lf30_yo2zavgg.json"  background="transparent"  speed="1"  style="width: 120px; height: 120px;"  loop  autoplay></lottie-player>
                        </div>

                        <div class="has-text-centered">
                            <h1 class="title">¡Gracias por tu compra en {{ name }}!</h1>
                            <p class="subtitle is-5 has-text-success">Número de orden: {{ orderId }} </p>

                            <p class="mb-5">En breve recibiras un mensaje con los detalles de tu pedido.</p>

                        </div>

                        <table class="table is-fullwidth">
                            <tbody>
                                {% autoescape off %}
                                {% for product, price in products.items %}
                                
                                    <tr>
                                        <td>{{ product }}</td>
                                        <td align="right">{{ currency }}{{ price }}</td>
                                    </tr>

                                {% endfor %}

                                
                                {% if delivery %}
                                <tr id='delivery-price'>
                                    <td>Envío a domicilio</td>
                                    <td align="right">{{ currency }}{{ delivery }}</td>
                                </tr>
                                
                                {% else %}

                                <tr id='delivery-price'>

                                </tr>

                                {% endif %}
                                    

                                <tfoot class="has-text-weight-bold">
                                    <td>Total pagado</td>
                                    <td id="cart-total" align="right">{{ currency }}{{ total }}</td>
                                </tfoot>
                                

                                {% endautoescape %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </section>

    
</body>
</html>